version: "3.8"
services:
  web: &web-recipe
    build:
      context: ./web_application
      dockerfile: webapp.dockerfile
    command: "python manage.py runserver 0.0.0.0:8080"
    environment:
      AMQP_ADDRESS: "amqp://guest:guest@rabbitmq:5672//"
    volumes:
      - ./web_application:/code
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    container_name: "chatroomies_web"
    stdin_open: true
    tty: true
  db:
    image: percona
    ports:
      - "3306:3306"
    volumes:
      - ./create_databases:/docker-entrypoint-initdb.d
    environment:
      "MYSQL_ALLOW_EMPTY_PASSWORD": "yes"
    container_name: "chatroomies_db"

  broker:
    image: rabbitmq:3.8.9-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  bot:
    build:
      context: ./bot_server
      dockerfile: bot.dockerfile
    command: "python main.py"
    volumes:
      - ./bot_server:/code
    depends_on:
      - broker
    container_name: "chatroomies_bot"
    stdin_open: true
    tty: true

  cmd_receiver:
    <<: *web-recipe
    ports:
      - "9090"
    container_name: "chatroomies_bot_receiver"
    command: "python manage.py cmd_receiver"
