name: Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  TestWebApplication:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r web_application/requirements/development.txt
    - name: Run tests and check for coverage
      run: |
        cd web_application
        py.test
  TestBot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot_server/requirements/development.txt
    - name: Run tests and check for coverage
      run: |
        cd bot_server
        python -m pytest
